# Generated by Django 5.0.1 on 2024-02-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contra1', models.CharField(max_length=150)),
                ('contra2', models.CharField(max_length=150)),
                ('contra3', models.CharField(max_length=150)),
                ('contra4', models.CharField(max_length=150)),
                ('contra5', models.CharField(max_length=150)),
                ('contra6', models.CharField(max_length=150)),
                ('contra7', models.CharField(max_length=150)),
                ('contra8', models.CharField(max_length=150)),
                ('contra9', models.CharField(max_length=150)),
            ],
        ),
    ]
